using Crolow.FastDico.Common.Models.ScrabbleApi.Game;

namespace Crolow.FastDico.ScrabbleApi.Extensions
{
    /// <summary>
    /// Provides helper methods for square pivot masks, pivot points, and pivot-letter counts.
    /// </summary>
    public static class SquareExtensions
    {
        /// <summary>
        /// Adds a letter to the pivot mask for the specified direction.
        /// </summary>
        /// <param name="sq">Square to update.</param>
        /// <param name="letter">Letter byte to allow as a pivot.</param>
        /// <param name="direction">Direction index to update.</param>
        public static void SetPivot(this Square sq, byte letter, int direction)
        {
            sq.Pivots[direction] = sq.Pivots[direction] | 1u << letter;
        }

        /// <summary>
        /// Sets the pivot points for the specified direction.
        /// </summary>
        /// <param name="sq">Square to update.</param>
        /// <param name="direction">Direction index to update.</param>
        /// <param name="points">Points generated by the cross word at this pivot.</param>
        public static void SetPivotPoints(this Square sq, int direction, int points)
        {
            sq.PivotPoints[direction] = points;
        }

        /// <summary>
        /// Replaces the pivot mask for the specified direction.
        /// </summary>
        /// <param name="sq">Square to update.</param>
        /// <param name="letter">Mask value to assign.</param>
        /// <param name="direction">Direction index to update.</param>
        public static void SetPivot(this Square sq, uint letter, int direction)
        {
            sq.Pivots[direction] = letter;
        }

        /// <summary>
        /// Sets the number of letters involved in the pivot for the specified direction.
        /// </summary>
        /// <param name="sq">Square to update.</param>
        /// <param name="letters">Number of connected letters.</param>
        /// <param name="direction">Direction index to update.</param>
        public static void SetPivotLetters(this Square sq, int letters, int direction)
        {
            sq.PivotLetters[direction] = letters;
        }

        /// <summary>
        /// Checks whether a tile can be placed according to the pivot mask.
        /// </summary>
        /// <param name="sq">Square to inspect.</param>
        /// <param name="letter">Tile to test.</param>
        /// <param name="direction">Direction index to inspect.</param>
        /// <param name="joker">Letter byte to use when the tile is a joker.</param>
        /// <param name="checkJoker">Indicates whether joker tiles should use <paramref name="joker"/> for the test.</param>
        /// <returns><c>true</c> when the pivot mask allows the tested letter.</returns>
        public static bool GetPivot(this Square sq, Tile letter, int direction, byte joker, bool checkJoker = true)
        {
            var c = (letter.IsJoker && checkJoker) ? joker : letter.Letter;
            return (sq.Pivots[direction] & 1u << c) > 0;
        }

        /// <summary>
        /// Checks whether a letter byte is allowed by the pivot mask.
        /// </summary>
        /// <param name="sq">Square to inspect.</param>
        /// <param name="direction">Direction index to inspect.</param>
        /// <param name="letter">Letter byte to test.</param>
        /// <returns><c>true</c> when the pivot mask allows the letter.</returns>
        public static bool GetPivot(this Square sq, int direction, byte letter)
        {
            return (sq.Pivots[direction] & 1u << letter) > 0;
        }

        /// <summary>
        /// Gets the raw pivot mask for a direction.
        /// </summary>
        /// <param name="sq">Square to inspect.</param>
        /// <param name="direction">Direction index to inspect.</param>
        /// <returns>The raw pivot mask value.</returns>
        public static uint GetPivot(this Square sq, int direction)
        {
            return sq.Pivots[direction];
        }

        /// <summary>
        /// Gets the number of connected letters for a pivot direction.
        /// </summary>
        /// <param name="sq">Square to inspect.</param>
        /// <param name="direction">Direction index to inspect.</param>
        /// <returns>The number of connected letters recorded for the pivot.</returns>
        public static int GetPivotLetters(this Square sq, int direction)
        {
            return sq.PivotLetters[direction];
        }

        /// <summary>
        /// Gets the points recorded for a pivot direction.
        /// </summary>
        /// <param name="sq">Square to inspect.</param>
        /// <param name="direction">Direction index to inspect.</param>
        /// <returns>The pivot points for the direction.</returns>
        public static int GetPivotPoints(this Square sq, int direction)
        {
            return sq.PivotPoints[direction];
        }


        /// <summary>
        /// Resets the pivot mask, points, and connected-letter count for a grid direction.
        /// </summary>
        /// <param name="sq">Square to reset.</param>
        /// <param name="grid">Direction index to reset.</param>
        /// <param name="points">Points to assign after reset.</param>
        /// <param name="maskValue">Mask value to assign after reset.</param>
        public static void ResetPivot(this Square sq, int grid, int points, uint maskValue = uint.MaxValue)
        {
            sq.Pivots[grid] = maskValue;
            sq.PivotPoints[grid] = points;
            sq.PivotLetters[grid] = 0;
        }


        /// <summary>
        /// Gets the pivot points for the supplied direction.
        /// </summary>
        /// <param name="sq">Square to inspect.</param>
        /// <param name="letter">Letter byte associated with the lookup.</param>
        /// <param name="direction">Direction index to inspect.</param>
        /// <returns>The pivot points recorded for the direction.</returns>
        public static int GetPivotPoint(this Square sq, byte letter, int direction)
        {
            return sq.PivotPoints[direction];
        }

    }
}
